name: Docker Builder
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - version.py

jobs:
  Docker-build:
    runs-on: ubuntu-latest
    name: Build Docker Image
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Release version
        id: release_version
        run: |
          app_version=$(cat version.py | sed -ne "s/APP_VERSION\s=\s'v\(.*\)'/\1/gp")
          echo "app_version=$app_version" >> $GITHUB_ENV

      - name: Docker Meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/moviepilot
          tags: |
            type=raw,value=${{ env.app_version }}
            type=raw,value=latest

      - name: Set Up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set Up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login Harbor
        run: echo "${{ secrets.HARBOR_PASSWORD }}" | docker login ${{ secrets.HARBOR_REGISTRY }} -u ${{ secrets.HARBOR_USERNAME }} --password-stdin

      - name: Build Image
        run: docker build -t ${{ secrets.HARBOR_REGISTRY }}/${{ secrets.DOCKER_USERNAME }}/moviepilot:${{ env.app_version }} .
      
      - name: Tag Image
        run: docker tag ${{ secrets.HARBOR_REGISTRY }}/${{ secrets.DOCKER_USERNAME }}/moviepilot:${{ env.app_version }} ${{ secrets.HARBOR_REGISTRY }}/${{ secrets.DOCKER_USERNAME }}/moviepilot:${{ secrets.TAG_VERSION }}

      - name: Push Image
        run: docker push ${{ secrets.HARBOR_REGISTRY }}/${{ secrets.DOCKER_USERNAME }}/moviepilot:${{ secrets.TAG_VERSION }}
